# -*- coding: utf-8 -*-
"""Api_handler.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jrtcqarJMJ7RVeOWigFDtCu98kE0EsHW
"""

import requests

def fetch_all_products():
    try:
        # Fetch products with limit=100 to get all available
        response = requests.get('https://dummyjson.com/products?limit=100')
        response.raise_for_status()  # Raises HTTPError for bad responses

        data = response.json()
        products = data['products']

        # Transform to expected format
        simplified_products = []
        for product in products:
            simplified_products.append({
                'id': product['id'],
                'title': product['title'],
                'category': product['category'],
                'brand': product['brand'],
                'price': product['price'],
                'rating': product['rating']
            })

        print(f"Successfully fetched {len(simplified_products)} products")
        return simplified_products

    except requests.exceptions.RequestException as e:
        print(f"Failed to fetch products: {e}")
        return []

def create_product_mapping(api_products):

    product_mapping = {}

    for product in api_products:
        product_id = product['id']
        product_mapping[product_id] = {
            'title': product['title'],
            'category': product['category'],
            'brand': product['brand'],
            'rating': product['rating']
        }

    return product_mapping

import os

def save_enriched_data(enriched_transactions, filename='data/enriched_sales_data.txt'):
    """ Saves enriched transactions back to file """
    # Create directory if it doesn't exist
    output_dir = os.path.dirname(filename)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    if not enriched_transactions:
        print("No transactions to save")
        return

    # Define all expected columns in order
    columns = [
        'TransactionID', 'Date', 'ProductID', 'ProductName', 'Quantity',
        'UnitPrice', 'CustomerID', 'Region', 'API_Category', 'API_Brand',
        'API_Rating', 'API_Match'
    ]

    # Write header
    header = '|'.join(columns)

    # Build data rows
    data_rows = []
    for transaction in enriched_transactions:
        row_values = []
        for col in columns:
            value = transaction.get(col, '')
            # Handle None values and convert to string
            if value is None:
                row_values.append('')
            else:
                row_values.append(str(value))
        data_rows.append('|'.join(row_values))

    # Write to file
    try:
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(header + '\n')
            f.write('\n'.join(data_rows) + '\n')

        print(f"Successfully saved {len(enriched_transactions)} transactions to {filename}")
    except IOError as e:
        print(f"Error writing to file {filename}: {e}")

def enrich_sales_data(transactions, product_mapping):
    """ save_enriched_data function"""
    enriched_transactions = []

    for transaction in transactions:
        enriched = transaction.copy()
        product_id_str = enriched.get('ProductID', '')
        numeric_id_match = re.search(r'P(\d+)', product_id_str)

        if numeric_id_match:
            try:
                product_id = int(numeric_id_match.group(1))
                if product_id in product_mapping:
                    api_info = product_mapping[product_id]
                    enriched.update({
                        'API_Category': api_info['category'],
                        'API_Brand': api_info['brand'],
                        'API_Rating': api_info['rating'],
                        'API_Match': True
                    })
                else:
                    enriched.update({
                        'API_Category': None, 'API_Brand': None,
                        'API_Rating': None, 'API_Match': False
                    })
            except (ValueError, KeyError):
                enriched.update({
                    'API_Category': None, 'API_Brand': None,
                    'API_Rating': None, 'API_Match': False
                })
        else:
            enriched.update({
                'API_Category': None, 'API_Brand': None,
                'API_Rating': None, 'API_Match': False
            })

        enriched_transactions.append(enriched)

    # Save using helper function
    save_enriched_data(enriched_transactions)
    return enriched_transactions